import java.util.ArrayList
Main

public static void main(String[] args) {
	ArrayList <String> players = new ArrayList<>();
	players.add ("Lucas");
	players.add ("Oliver");
	players.add ("Louise");
	Team t = new Team ("Mhaa",2,players);

	t.setRank(3);

	ArrayList <String> players1 = new ArrayList<>();
	players1.add ("")

	Team t1 = new Team ("louise", 5 players1);
	players1.add("Kasper");
	players1.add ("Frank");
	players1.add ("Line");





}